### ISSUE TITLE
PPI adapter does not work if not all fields are selected

### ISSUE THREAD

**Issue by slobentanzer** [HUBioDataLab/CROssBAR-BioCypher-Migration#5]
if you select less than all edge fields (eg the intact edge fields), the adapter fails because the column name re-assignment (eg https://github.com/HUBioDataLab/CROssBAR-BioCypher-Migration/blob/b7062ec2f55da787888f1ef8e4b46a229217f46a/bccb/ppi_adapter.py#L158) is not interactive (column names are hardcoded).

**Comment by bnymnsen** [comment]
Currently, ppi adapter heavily dependent on some fields (e.g., pubmed ids or uniprot ids) to do aggregation and merging operations. For example:
https://github.com/HUBioDataLab/CROssBAR-BioCypher-Migration/blob/b7062ec2f55da787888f1ef8e4b46a229217f46a/bccb/ppi_adapter.py#L173
https://github.com/HUBioDataLab/CROssBAR-BioCypher-Migration/blob/ba433aaedd3583693fd9779b2594282446e1f61d/bccb/ppi_adapter.py#L466

I can fix that but it might still create errors due to the operations in the following lines. 

I felt like I have to hardcode these column names because "pubmeds" in Intact and "pmid" in Biogrid mean same thing. Similarly, "methods" and "experimental_system" correspond to the same thing. So, if the user wants to use these fields as well as wants to merge them, the script should be aware of they basically correspond to same thing. I guess if I think about a bit, I can find a way to get around this problem. However, I think, I have to enforce the existence of uniprot_a and uniprot_b fields regardless of user choice because the whole thing depends on existence these fields.

**Comment by slobentanzer** [comment]
IMO, the fields should be organised like this:
- mandatory fields: if they are mandatory for the functionality of the adapter, the user does not have a choice. We don't need an enum in that case. They can be hardcoded and will not even be mentioned in the script. If you do want to provide them as enum for completeness, just include a check at the beginning that throws an error with an informative message á la `you cannot call the uniprot adapter without the uniprot accession field`.
- optional fields: if they are not necessary for the adapter to function, they can be enums and accessed in the script (or via config. However, if the user can select them, you need to be aware which ones will be processed and modify the column selection and renaming process. For example, you can make a lookup dictionary with the corresponding spellings and create a list from only the selected ones. Most important is that in this case, the columns are assigned in an interactive manner.

Do you know what I mean?

**Comment by slobentanzer** [comment]
> I felt like I have to hardcode these column names because "pubmeds" in Intact and "pmid" in Biogrid mean same thing. 

See my response [here](https://github.com/HUBioDataLab/CROssBAR-BioCypher-Migration/issues/6#issuecomment-1366034983) on how to merge similar concepts inside of BioCypher instead of writing extensive manual logic in the adapter. I would advocate for just passing on the thing however it is called at the source and then updating the BioCypher schema configuration to reflect these spellings.

**Comment by bnymnsen** [comment]
> Do you know what I mean?

Yeah, I get what you meant. I will try to implement mandatory and optional fields in the script.

**Comment by bnymnsen** [comment]
I added and tested using default dictionary in the script. Process functions look like working with field selection. I think, simply, copying individual database functions in ppi adapter and pasting to an adapter script of particular database should also work for modularization case. Will do it as well. Also, I will refactor ```merge_all``` function (For now, it may give errors when fields are selected).
